# Generated by Django 2.2 on 2019-04-05 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='RestaurantsPriceRange2',
            field=models.SmallIntegerField(),
        ),
    ]
